[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = { version = "2.5.0", features = ["serde"] }
regex = "1.5"
http = "1.0.0"
serde = "1.0.195"
serde_json = "1.0.111"